apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: throw-dice-cronjob
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: throw-dice-cronjob
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: nginx
            name: throw-dice-cronjob
            resources: {}
          restartPolicy: OnFailure
  schedule: '30 21 * * * '
status: {}
