apiVersion: apps/v1
kind: ingress
metadata:
   name: ingress-wear-watch
spec:
 rules:
  - http:
    - paths: /wear
      backend:
       serviceName: wear-service
       servicePort: 80
    - paths: /watch
      backend:
       serviceName: watch-service
       servicePort: 80