apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: redis
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: redis
        name: redis
        resources: {}
      restartPolicy: Never
  completions: 10
  parallelism: 5
status: {}
