apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx2
  name: nginx2
spec:
  containers:
  - image: nginx
    name: nginx2
    resources: {}
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: secfile
            key: username
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
