apiVersion: v1
kind: Pod
metadata:
    name: myapp-pod
    labels:
        app: myapp
        type: front-end

spec:
  securityContext:
    runAsUser: 1010
  containers:
        - name: nginx-container
          image: nginx
        
    
